#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BloodDecal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BloodDecal.BP_BloodDecal_C
// 0x0018 (0x02B0 - 0x0298)
class ABP_BloodDecal_C final : public ADecalActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Plane;                                             // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               BloodDecalMaterialRef;                             // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BloodDecal(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BloodDecal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BloodDecal_C")
	}
	static class ABP_BloodDecal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BloodDecal_C>();
	}
};
DUMPER7_ASSERTS_ABP_BloodDecal_C;

}

