#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameArmor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_GameArmor.BP_GameArmor_C.Initialize
// 0x0004 (0x0004 - 0x0000)
struct BP_GameArmor_C_Initialize final
{
public:
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_GameArmor_C_Initialize;

}

