#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameItem

#include "Basic.hpp"

#include "BP_GameItem_classes.hpp"


namespace SDK
{

// Function BP_GameItem.BP_GameItem_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_GameItem_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameItem_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}

}

