#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generator_CombatEvent_Random

#include "Basic.hpp"

#include "BP_Generator_CombatEvent_Random_classes.hpp"
#include "BP_Generator_CombatEvent_Random_parameters.hpp"


namespace SDK
{

// Function BP_Generator_CombatEvent_Random.BP_Generator_CombatEvent_Random_C.ExecuteUbergraph_BP_Generator_CombatEvent_Random
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Generator_CombatEvent_Random_C::ExecuteUbergraph_BP_Generator_CombatEvent_Random(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generator_CombatEvent_Random_C", "ExecuteUbergraph_BP_Generator_CombatEvent_Random");

	Params::BP_Generator_CombatEvent_Random_C_ExecuteUbergraph_BP_Generator_CombatEvent_Random Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Generator_CombatEvent_Random.BP_Generator_CombatEvent_Random_C.Generate Combat Event
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Tourney                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStr_Passport_CombatEvent1*      Passport                                               (Parm, OutParm, HasGetValueTypeHash)

void ABP_Generator_CombatEvent_Random_C::Generate_Combat_Event(bool Tourney, struct FStr_Passport_CombatEvent1* Passport)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generator_CombatEvent_Random_C", "Generate Combat Event");

	Params::BP_Generator_CombatEvent_Random_C_Generate_Combat_Event Parms{};

	Parms.Tourney = Tourney;

	UObject::ProcessEvent(Func, &Parms);

	if (Passport != nullptr)
		*Passport = std::move(Parms.Passport);
}


// Function BP_Generator_CombatEvent_Random.BP_Generator_CombatEvent_Random_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Generator_CombatEvent_Random_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generator_CombatEvent_Random_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

