#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generator_CombatEvent_Random

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Enum_Ranks_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Generator_CombatEvent_Random.BP_Generator_CombatEvent_Random_C
// 0x0018 (0x02A8 - 0x0290)
class ABP_Generator_CombatEvent_Random_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGI_Settings_C*                         As_GI_Settings;                                    // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Generator_CombatEvent_Random(int32 EntryPoint);
	void Generate_Combat_Event(bool Tourney, struct FStr_Passport_CombatEvent1* Passport);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Generator_CombatEvent_Random_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Generator_CombatEvent_Random_C")
	}
	static class ABP_Generator_CombatEvent_Random_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Generator_CombatEvent_Random_C>();
	}
};
DUMPER7_ASSERTS_ABP_Generator_CombatEvent_Random_C;

}

