#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameArmor

#include "Basic.hpp"

#include "BP_GameArmor_classes.hpp"
#include "BP_GameArmor_parameters.hpp"


namespace SDK
{

// Function BP_GameArmor.BP_GameArmor_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_GameArmor_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameArmor_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}

}

