#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generator_Armor_Random

#include "Basic.hpp"

#include "BP_Generator_Armor_Random_classes.hpp"
#include "BP_Generator_Armor_Random_parameters.hpp"


namespace SDK
{

// Function BP_Generator_Armor_Random.BP_Generator_Armor_Random_C.Generate Armor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// Enum_Ranks                              Tier                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EArmorSlots_Enum                        Slot                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Module_Spawn_Chance                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Mercenary_Colors                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStr_Passport_Armor1*            Armor_Passport                                         (Parm, OutParm, HasGetValueTypeHash)

void ABP_Generator_Armor_Random_C::Generate_Armor(Enum_Ranks Tier, EArmorSlots_Enum Slot, double Module_Spawn_Chance, bool Mercenary_Colors, struct FStr_Passport_Armor1* Armor_Passport)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Generator_Armor_Random_C", "Generate Armor");

	Params::BP_Generator_Armor_Random_C_Generate_Armor Parms{};

	Parms.Tier = Tier;
	Parms.Slot = Slot;
	Parms.Module_Spawn_Chance = Module_Spawn_Chance;
	Parms.Mercenary_Colors = Mercenary_Colors;

	UObject::ProcessEvent(Func, &Parms);

	if (Armor_Passport != nullptr)
		*Armor_Passport = std::move(Parms.Armor_Passport);
}

}

