#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trash_ColoredBall

#include "Basic.hpp"

#include "BP_Trash_ColoredBall_classes.hpp"
#include "BP_Trash_ColoredBall_parameters.hpp"


namespace SDK
{

// Function BP_Trash_ColoredBall.BP_Trash_ColoredBall_C.ExecuteUbergraph_BP_Trash_ColoredBall
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Trash_ColoredBall_C::ExecuteUbergraph_BP_Trash_ColoredBall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trash_ColoredBall_C", "ExecuteUbergraph_BP_Trash_ColoredBall");

	Params::BP_Trash_ColoredBall_C_ExecuteUbergraph_BP_Trash_ColoredBall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Trash_ColoredBall.BP_Trash_ColoredBall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Trash_ColoredBall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trash_ColoredBall_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Trash_ColoredBall.BP_Trash_ColoredBall_C.Turn Blue
// (BlueprintCallable, BlueprintEvent)

void ABP_Trash_ColoredBall_C::Turn_Blue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trash_ColoredBall_C", "Turn Blue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Trash_ColoredBall.BP_Trash_ColoredBall_C.Turn Green
// (BlueprintCallable, BlueprintEvent)

void ABP_Trash_ColoredBall_C::Turn_Green()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trash_ColoredBall_C", "Turn Green");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Trash_ColoredBall.BP_Trash_ColoredBall_C.Turn Red
// (BlueprintCallable, BlueprintEvent)

void ABP_Trash_ColoredBall_C::Turn_Red()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trash_ColoredBall_C", "Turn Red");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Trash_ColoredBall.BP_Trash_ColoredBall_C.Turn Yellow
// (BlueprintCallable, BlueprintEvent)

void ABP_Trash_ColoredBall_C::Turn_Yellow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Trash_ColoredBall_C", "Turn Yellow");

	UObject::ProcessEvent(Func, nullptr);
}

}

