#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Weapon_Treasure_Paten_001

#include "Basic.hpp"

#include "ModularWeaponBP_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Weapon_Treasure_Paten_001.BP_Weapon_Treasure_Paten_001_C
// 0x0020 (0x0BD8 - 0x0BB8)
class ABP_Weapon_Treasure_Paten_001_C final : public AModularWeaponBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Weapon_Treasure_Paten_001_C;     // 0x0BB8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        Base1_0;                                           // 0x0BC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Tip1;                                              // 0x0BC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Goblet;                                            // 0x0BD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Buckler_Buckler_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void ExecuteUbergraph_BP_Weapon_Treasure_Paten_001(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Weapon_Treasure_Paten_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Weapon_Treasure_Paten_001_C")
	}
	static class ABP_Weapon_Treasure_Paten_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Weapon_Treasure_Paten_001_C>();
	}
};
DUMPER7_ASSERTS_ABP_Weapon_Treasure_Paten_001_C;

}

