#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Weapon_Ranged_Projectle_Master

#include "Basic.hpp"

#include "BP_Weapon_Ranged_Projectle_Master_classes.hpp"
#include "BP_Weapon_Ranged_Projectle_Master_parameters.hpp"


namespace SDK
{

// Function BP_Weapon_Ranged_Projectle_Master.BP_Weapon_Ranged_Projectle_Master_C.ExecuteUbergraph_BP_Weapon_Ranged_Projectle_Master
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Weapon_Ranged_Projectle_Master_C::ExecuteUbergraph_BP_Weapon_Ranged_Projectle_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Weapon_Ranged_Projectle_Master_C", "ExecuteUbergraph_BP_Weapon_Ranged_Projectle_Master");

	Params::BP_Weapon_Ranged_Projectle_Master_C_ExecuteUbergraph_BP_Weapon_Ranged_Projectle_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Weapon_Ranged_Projectle_Master.BP_Weapon_Ranged_Projectle_Master_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Weapon_Ranged_Projectle_Master_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Weapon_Ranged_Projectle_Master_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Weapon_Ranged_Projectle_Master.BP_Weapon_Ranged_Projectle_Master_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Weapon_Ranged_Projectle_Master_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Weapon_Ranged_Projectle_Master_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

