#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CanParry

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_CanParry.BPI_CanParry_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_CanParry_C final
{
public:
	void Send_Threat_Location_R(const struct FVector& Threat_Location, const struct FVector& Offset, bool Immediate, bool* Nul);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_CanParry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_CanParry_C")
	}
	static class IBPI_CanParry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_CanParry_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_CanParry_C;

}

