#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ApplySettings

#include "Basic.hpp"

#include "BPI_ApplySettings_classes.hpp"
#include "BPI_ApplySettings_parameters.hpp"


namespace SDK
{

// Function BPI_ApplySettings.BPI_ApplySettings_C.Apply Settings
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  FOV                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_ApplySettings_C::Apply_Settings(double FOV)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_ApplySettings_C", "Apply Settings");

	Params::BPI_ApplySettings_C_Apply_Settings Parms{};

	Parms.FOV = FOV;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

