#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DA_Character_Names_Master

#include "Basic.hpp"

#include "DA_Character_Names_Master_classes.hpp"
#include "DA_Character_Names_Master_parameters.hpp"


namespace SDK
{

// Function DA_Character_Names_Master.DA_Character_Names_Master_C.Generate Name
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName*                            Name_0                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDA_Character_Names_Master_C::Generate_Name(class FName* Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DA_Character_Names_Master_C", "Generate Name");

	Params::DA_Character_Names_Master_C_Generate_Name Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Name_0 != nullptr)
		*Name_0 = Parms.Name_0;
}

}

