#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DA_FreeMode_Inventory

#include "Basic.hpp"

#include "Str_Inventory_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DA_FreeMode_Inventory.DA_FreeMode_Inventory_C
// 0x0020 (0x0050 - 0x0030)
class UDA_FreeMode_Inventory_C final : public UPrimaryDataAsset
{
public:
	struct FStr_Inventory                         Inventory;                                         // 0x0030(0x0020)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DA_FreeMode_Inventory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DA_FreeMode_Inventory_C")
	}
	static class UDA_FreeMode_Inventory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDA_FreeMode_Inventory_C>();
	}
};
DUMPER7_ASSERTS_UDA_FreeMode_Inventory_C;

}

