#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENUM_Languages

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENUM_Languages.ENUM_Languages
// NumValues: 0x0006
enum class ENUM_Languages : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	ENUM_MAX                                 = 5,
};

}

