#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_DismembermentPart

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_DismembermentPart.Enum_DismembermentPart
// NumValues: 0x0010
enum class Enum_DismembermentPart : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator14                          = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator4                           = 5,
	NewEnumerator5                           = 6,
	NewEnumerator6                           = 7,
	NewEnumerator7                           = 8,
	NewEnumerator8                           = 9,
	NewEnumerator9                           = 10,
	NewEnumerator10                          = 11,
	NewEnumerator11                          = 12,
	NewEnumerator12                          = 13,
	NewEnumerator13                          = 14,
	Enum_MAX                                 = 15,
};

}

