#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_SheathSlot_Concrete

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_SheathSlot_Concrete.Enum_SheathSlot_Concrete
// NumValues: 0x000D
enum class Enum_SheathSlot_Concrete : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator6                           = 5,
	NewEnumerator7                           = 6,
	NewEnumerator8                           = 7,
	NewEnumerator9                           = 8,
	NewEnumerator10                          = 9,
	NewEnumerator5                           = 10,
	NewEnumerator11                          = 11,
	Enum_SheathSlot_MAX                      = 12,
};

}

