#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GBP_TestCouter_R

#include "Basic.hpp"

#include "BP_GameArmor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GBP_TestCouter_R.GBP_TestCouter_R_C
// 0x0000 (0x00C8 - 0x00C8)
class UGBP_TestCouter_R_C final : public UBP_GameArmor_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GBP_TestCouter_R_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GBP_TestCouter_R_C")
	}
	static class UGBP_TestCouter_R_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGBP_TestCouter_R_C>();
	}
};
DUMPER7_ASSERTS_UGBP_TestCouter_R_C;

}

