#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Map_Menu_Startup

#include "Basic.hpp"


namespace SDK::Params
{

// Function Map_Menu_Startup.Map_Menu_Startup_C.ExecuteUbergraph_Map_Menu_Startup
// 0x0010 (0x0010 - 0x0000)
struct Map_Menu_Startup_C_ExecuteUbergraph_Map_Menu_Startup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Startup_Menu_C*                     CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Map_Menu_Startup_C_ExecuteUbergraph_Map_Menu_Startup;

}

