#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModularWeaponBP_Tool_Flail

#include "Basic.hpp"


namespace SDK::Params
{

// Function ModularWeaponBP_Tool_Flail.ModularWeaponBP_Tool_Flail_C.ExecuteUbergraph_ModularWeaponBP_Tool_Flail
// 0x0008 (0x0008 - 0x0000)
struct ModularWeaponBP_Tool_Flail_C_ExecuteUbergraph_ModularWeaponBP_Tool_Flail final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ModularWeaponBP_Tool_Flail_C_ExecuteUbergraph_ModularWeaponBP_Tool_Flail;

// Function ModularWeaponBP_Tool_Flail.ModularWeaponBP_Tool_Flail_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct ModularWeaponBP_Tool_Flail_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ModularWeaponBP_Tool_Flail_C_ReceiveTick;

}

