#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Modular_Weapon_Polearm_Haft_Master

#include "Basic.hpp"

#include "Modular_Weapon_Grip_classes.hpp"
#include "Enum_MaterialQuality_structs.hpp"
#include "Enum_MaterialLayer_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Modular_Weapon_Polearm_Haft_Master.Modular_Weapon_Polearm_Haft_Master_C
// 0x0000 (0x05F8 - 0x05F8)
class AModular_Weapon_Polearm_Haft_Master_C : public AModular_Weapon_Grip_C
{
public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Modular_Weapon_Polearm_Haft_Master_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Modular_Weapon_Polearm_Haft_Master_C")
	}
	static class AModular_Weapon_Polearm_Haft_Master_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModular_Weapon_Polearm_Haft_Master_C>();
	}
};
DUMPER7_ASSERTS_AModular_Weapon_Polearm_Haft_Master_C;

}

