#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Modular_Sword_Blade_G_110

#include "Basic.hpp"

#include "Modular_Sword_Blade_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Modular_Sword_Blade_G_110.Modular_Sword_Blade_G_110_C
// 0x0000 (0x0448 - 0x0448)
class AModular_Sword_Blade_G_110_C final : public AModular_Sword_Blade_Master_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Modular_Sword_Blade_G_110_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Modular_Sword_Blade_G_110_C")
	}
	static class AModular_Sword_Blade_G_110_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AModular_Sword_Blade_G_110_C>();
	}
};
DUMPER7_ASSERTS_AModular_Sword_Blade_G_110_C;

}

