#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Modular_Weapon_Module

#include "Basic.hpp"

#include "Modular_Weapon_Module_classes.hpp"
#include "Modular_Weapon_Module_parameters.hpp"


namespace SDK
{

// Function Modular_Weapon_Module.Modular_Weapon_Module_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AModular_Weapon_Module_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Modular_Weapon_Module_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

