#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_Medieval_Color_Swatches

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct Str_Medieval_Color_Swatches.Str_Medieval_Color_Swatches
// 0x0028 (0x0028 - 0x0000)
struct FStr_Medieval_Color_Swatches final
{
public:
	TArray<struct FLinearColor>                   Swatch_3_D15E73BA4E825EE7BDA93C9B4BA6F43E;         // 0x0000(0x0010)(Edit, BlueprintVisible)
	struct FLinearColor                           Color_8_48D3439746394A73E880D1817B291CE6;          // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SetColor_5_30D1617146669CE43AD538B674B739FA;       // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_Medieval_Color_Swatches;

}

