#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CharacterCreation

#include "Basic.hpp"

#include "UI_CharacterCreation_classes.hpp"
#include "UI_CharacterCreation_parameters.hpp"


namespace SDK
{

// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Button_0_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Button_0_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Button_0_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Button_0_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Button_0_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Button_0_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Button_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Button_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Button_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Button_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Button_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Button_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_EditableText_0_K2Node_ComponentBoundEvent_6_OnEditableTextChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_EditableText_0_K2Node_ComponentBoundEvent_6_OnEditableTextChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_EditableText_0_K2Node_ComponentBoundEvent_6_OnEditableTextChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_EditableText_0_K2Node_ComponentBoundEvent_6_OnEditableTextChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Player_Items_List_K2Node_ComponentBoundEvent_8_OnListEntryInitializedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Player_Items_List_K2Node_ComponentBoundEvent_8_OnListEntryInitializedDynamic__DelegateSignature(class UObject* Item, class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Player_Items_List_K2Node_ComponentBoundEvent_8_OnListEntryInitializedDynamic__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Player_Items_List_K2Node_ComponentBoundEvent_8_OnListEntryInitializedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Slider_1_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Slider_1_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Slider_1_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Slider_1_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Slider_2_K2Node_ComponentBoundEvent_3_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Slider_2_K2Node_ComponentBoundEvent_3_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Slider_2_K2Node_ComponentBoundEvent_3_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Slider_2_K2Node_ComponentBoundEvent_3_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Slider_3_K2Node_ComponentBoundEvent_4_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Slider_3_K2Node_ComponentBoundEvent_4_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Slider_3_K2Node_ComponentBoundEvent_4_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Slider_3_K2Node_ComponentBoundEvent_4_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Slider_4_K2Node_ComponentBoundEvent_5_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Slider_4_K2Node_ComponentBoundEvent_5_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Slider_4_K2Node_ComponentBoundEvent_5_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Slider_4_K2Node_ComponentBoundEvent_5_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Slider_5_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Slider_5_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Slider_5_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Slider_5_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Slider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Slider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Slider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Slider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_11_SimpleListItemEventDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_11_SimpleListItemEventDynamic__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_11_SimpleListItemEventDynamic__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_11_SimpleListItemEventDynamic__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_12_OnItemIsHoveredChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_12_OnItemIsHoveredChangedDynamic__DelegateSignature(class UObject* Item, bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_12_OnItemIsHoveredChangedDynamic__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_12_OnItemIsHoveredChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_9_OnListEntryInitializedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_9_OnListEntryInitializedDynamic__DelegateSignature(class UObject* Item, class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_9_OnListEntryInitializedDynamic__DelegateSignature");

	Params::UI_CharacterCreation_C_BndEvt__UI_CharacterCreation_Trader_Items_List_K2Node_ComponentBoundEvent_9_OnListEntryInitializedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_CharacterCreation_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.ExecuteUbergraph_UI_CharacterCreation
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::ExecuteUbergraph_UI_CharacterCreation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "ExecuteUbergraph_UI_CharacterCreation");

	Params::UI_CharacterCreation_C_ExecuteUbergraph_UI_CharacterCreation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Generate Tier Weapons
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FStr_Passport_Weapon1>&TargetArray                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// Enum_Ranks                              Tier                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::Generate_Tier_Weapons(const TArray<struct FStr_Passport_Weapon1>& TargetArray, Enum_Ranks Tier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Generate Tier Weapons");

	Params::UI_CharacterCreation_C_Generate_Tier_Weapons Parms{};

	Parms.TargetArray = std::move(TargetArray);
	Parms.Tier = Tier;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Get_Slider_Background_Value
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_CharacterCreation_C::Get_Slider_Background_Value()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Get_Slider_Background_Value");

	Params::UI_CharacterCreation_C_Get_Slider_Background_Value Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Get_Slider_EyeColor_Value
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_CharacterCreation_C::Get_Slider_EyeColor_Value()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Get_Slider_EyeColor_Value");

	Params::UI_CharacterCreation_C_Get_Slider_EyeColor_Value Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Get_Slider_Face_Value
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_CharacterCreation_C::Get_Slider_Face_Value()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Get_Slider_Face_Value");

	Params::UI_CharacterCreation_C_Get_Slider_Face_Value Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Get_Slider_Hair_Value
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_CharacterCreation_C::Get_Slider_Hair_Value()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Get_Slider_Hair_Value");

	Params::UI_CharacterCreation_C_Get_Slider_Hair_Value Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Get_Slider_HairColor_Value
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_CharacterCreation_C::Get_Slider_HairColor_Value()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Get_Slider_HairColor_Value");

	Params::UI_CharacterCreation_C_Get_Slider_HairColor_Value Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Get_Slider_Stature_Value
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_CharacterCreation_C::Get_Slider_Stature_Value()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Get_Slider_Stature_Value");

	Params::UI_CharacterCreation_C_Get_Slider_Stature_Value Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.GetBrush
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_CharacterCreation_C::GetBrush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "GetBrush");

	Params::UI_CharacterCreation_C_GetBrush Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.GetColorAndOpacity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_CharacterCreation_C::GetColorAndOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "GetColorAndOpacity");

	Params::UI_CharacterCreation_C_GetColorAndOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.GetColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UUI_CharacterCreation_C::GetColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "GetColorAndOpacity_0");

	Params::UI_CharacterCreation_C_GetColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.GetText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_CharacterCreation_C::GetText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "GetText");

	Params::UI_CharacterCreation_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_CharacterCreation_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "GetText_0");

	Params::UI_CharacterCreation_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "PreConstruct");

	Params::UI_CharacterCreation_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CharacterCreation.UI_CharacterCreation_C.Set Up Trader Item
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Trader                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CharacterCreation_C::Set_Up_Trader_Item(class UObject* Item, class UObject* Widget, bool Trader)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CharacterCreation_C", "Set Up Trader Item");

	Params::UI_CharacterCreation_C_Set_Up_Trader_Item Parms{};

	Parms.Item = Item;
	Parms.Widget = Widget;
	Parms.Trader = Trader;

	UObject::ProcessEvent(Func, &Parms);
}

}

