#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ColorPicker_Widget

#include "Basic.hpp"

#include "UI_ColorPicker_Widget_classes.hpp"
#include "UI_ColorPicker_Widget_parameters.hpp"


namespace SDK
{

// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEventSynth2D__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ColorPicker_Widget_C::BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEventSynth2D__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEventSynth2D__DelegateSignature");

	Params::UI_ColorPicker_Widget_C_BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEventSynth2D__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEventSynth2D__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ColorPicker_Widget_C::BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEventSynth2D__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEventSynth2D__DelegateSignature");

	Params::UI_ColorPicker_Widget_C_BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEventSynth2D__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_2_OnMouseCaptureEndEventSynth2D__DelegateSignature
// (BlueprintEvent)

void UUI_ColorPicker_Widget_C::BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_2_OnMouseCaptureEndEventSynth2D__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "BndEvt__UI_ColorPicker_Widget_Synth2DSlider_201_K2Node_ComponentBoundEvent_2_OnMouseCaptureEndEventSynth2D__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.ExecuteUbergraph_UI_ColorPicker_Widget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ColorPicker_Widget_C::ExecuteUbergraph_UI_ColorPicker_Widget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "ExecuteUbergraph_UI_ColorPicker_Widget");

	Params::UI_ColorPicker_Widget_C_ExecuteUbergraph_UI_ColorPicker_Widget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ColorPicker_Widget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "PreConstruct");

	Params::UI_ColorPicker_Widget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.Set New Value Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 New_Value                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ColorPicker_Widget_C::Set_New_Value_Event(const struct FVector2D& New_Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "Set New Value Event");

	Params::UI_ColorPicker_Widget_C_Set_New_Value_Event Parms{};

	Parms.New_Value = std::move(New_Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ColorPicker_Widget.UI_ColorPicker_Widget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ColorPicker_Widget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ColorPicker_Widget_C", "Tick");

	Params::UI_ColorPicker_Widget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

