#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Dialog_Widget_Innkeeper_NoMoney

#include "Basic.hpp"

#include "UI_Dialog_Widget_Innkeeper_NoMoney_classes.hpp"
#include "UI_Dialog_Widget_Innkeeper_NoMoney_parameters.hpp"


namespace SDK
{

// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.BndEvt__UI_Dialog_Widget_Innkeeper_Errand_Barrel_Button_3_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::BndEvt__UI_Dialog_Widget_Innkeeper_Errand_Barrel_Button_3_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "BndEvt__UI_Dialog_Widget_Innkeeper_Errand_Barrel_Button_3_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.BndEvt__UI_Dialog_Widget_Merchant_Button_3_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::BndEvt__UI_Dialog_Widget_Merchant_Button_3_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "BndEvt__UI_Dialog_Widget_Merchant_Button_3_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.ExecuteUbergraph_UI_Dialog_Widget_Innkeeper_NoMoney
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::ExecuteUbergraph_UI_Dialog_Widget_Innkeeper_NoMoney(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "ExecuteUbergraph_UI_Dialog_Widget_Innkeeper_NoMoney");

	Params::UI_Dialog_Widget_Innkeeper_NoMoney_C_ExecuteUbergraph_UI_Dialog_Widget_Innkeeper_NoMoney Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Dialog_Widget_Innkeeper_NoMoney.UI_Dialog_Widget_Innkeeper_NoMoney_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Dialog_Widget_Innkeeper_NoMoney_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Innkeeper_NoMoney_C", "PreConstruct");

	Params::UI_Dialog_Widget_Innkeeper_NoMoney_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

