#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Dialog_Widget_Seer_GoToHell

#include "Basic.hpp"

#include "UI_Dialog_Widget_Seer_GoToHell_classes.hpp"
#include "UI_Dialog_Widget_Seer_GoToHell_parameters.hpp"


namespace SDK
{

// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.BndEvt__UI_Dialog_Widget_Innkeeper_Welcome_Button_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Seer_GoToHell_C::BndEvt__UI_Dialog_Widget_Innkeeper_Welcome_Button_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "BndEvt__UI_Dialog_Widget_Innkeeper_Welcome_Button_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Seer_GoToHell_C::BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Seer_GoToHell_C::BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "BndEvt__UI_Dialog_Widget_Merchant_Button_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.BndEvt__UI_Dialog_Widget_Seer_GoToHell_Slider_5_K2Node_ComponentBoundEvent_6_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Dialog_Widget_Seer_GoToHell_C::BndEvt__UI_Dialog_Widget_Seer_GoToHell_Slider_5_K2Node_ComponentBoundEvent_6_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "BndEvt__UI_Dialog_Widget_Seer_GoToHell_Slider_5_K2Node_ComponentBoundEvent_6_OnFloatValueChangedEvent__DelegateSignature");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_BndEvt__UI_Dialog_Widget_Seer_GoToHell_Slider_5_K2Node_ComponentBoundEvent_6_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.BndEvt__UI_Dialog_Widget_Seer_Greeting_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Dialog_Widget_Seer_GoToHell_C::BndEvt__UI_Dialog_Widget_Seer_Greeting_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "BndEvt__UI_Dialog_Widget_Seer_Greeting_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Dialog_Widget_Seer_GoToHell_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.ExecuteUbergraph_UI_Dialog_Widget_Seer_GoToHell
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Dialog_Widget_Seer_GoToHell_C::ExecuteUbergraph_UI_Dialog_Widget_Seer_GoToHell(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "ExecuteUbergraph_UI_Dialog_Widget_Seer_GoToHell");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_ExecuteUbergraph_UI_Dialog_Widget_Seer_GoToHell Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.GetText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Dialog_Widget_Seer_GoToHell_C::GetText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "GetText");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Dialog_Widget_Seer_GoToHell_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "GetText_0");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.GetText_1
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Dialog_Widget_Seer_GoToHell_C::GetText_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "GetText_1");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_GetText_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.GetValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_Dialog_Widget_Seer_GoToHell_C::GetValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "GetValue");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_GetValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Dialog_Widget_Seer_GoToHell_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "GetVisibility_0");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.GetVisibility_1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Dialog_Widget_Seer_GoToHell_C::GetVisibility_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "GetVisibility_1");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_GetVisibility_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Dialog_Widget_Seer_GoToHell.UI_Dialog_Widget_Seer_GoToHell_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Dialog_Widget_Seer_GoToHell_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Dialog_Widget_Seer_GoToHell_C", "PreConstruct");

	Params::UI_Dialog_Widget_Seer_GoToHell_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

