#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Pause_Eng

#include "Basic.hpp"

#include "UI_Pause_Eng_classes.hpp"
#include "UI_Pause_Eng_parameters.hpp"


namespace SDK
{

// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__Pause_UI_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__Pause_UI_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__Pause_UI_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__Pause_UI_ButtonSettings_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__Pause_UI_ButtonSettings_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__Pause_UI_ButtonSettings_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonContinue_K2Node_ComponentBoundEvent_12_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonContinue_K2Node_ComponentBoundEvent_12_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonContinue_K2Node_ComponentBoundEvent_12_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonContinue_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonContinue_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonContinue_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonQit_1_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_11_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_11_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_11_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonQit_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonSettings_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonSettings_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonSettings_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_ButtonSettings_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_ButtonSettings_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_ButtonSettings_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_Desktop_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_15_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Pause_Eng_C::BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "BndEvt__UI_Pause_Menu_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Pause_Eng_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.ExecuteUbergraph_UI_Pause_Eng
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Pause_Eng_C::ExecuteUbergraph_UI_Pause_Eng(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "ExecuteUbergraph_UI_Pause_Eng");

	Params::UI_Pause_Eng_C_ExecuteUbergraph_UI_Pause_Eng Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.Get_ProgressLostText_Text
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Pause_Eng_C::Get_ProgressLostText_Text()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "Get_ProgressLostText_Text");

	Params::UI_Pause_Eng_C_Get_ProgressLostText_Text Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.GetLastOpenedWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Pause_Eng_C::GetLastOpenedWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "GetLastOpenedWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.GetText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Pause_Eng_C::GetText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "GetText");

	Params::UI_Pause_Eng_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.GetText_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Pause_Eng_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "GetText_0");

	Params::UI_Pause_Eng_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.SetLastOpenedWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           UW                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Pause_Eng_C::SetLastOpenedWidget(class UClass* UW)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "SetLastOpenedWidget");

	Params::UI_Pause_Eng_C_SetLastOpenedWidget Parms{};

	Parms.UW = UW;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Pause_Eng.UI_Pause_Eng_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Pause_Eng_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Pause_Eng_C", "Tick");

	Params::UI_Pause_Eng_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

