#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Tavern_Mercenaries

#include "Basic.hpp"

#include "UI_Tavern_Mercenaries_classes.hpp"
#include "UI_Tavern_Mercenaries_parameters.hpp"


namespace SDK
{

// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Inventory_Button_K2Node_ComponentBoundEvent_22_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Inventory_Button_K2Node_ComponentBoundEvent_22_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Inventory_Button_K2Node_ComponentBoundEvent_22_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Inventory_Button_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Inventory_Button_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Inventory_Button_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Inventory_Player_Items_List_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Inventory_Player_Items_List_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature(class UObject* Item_0, class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Inventory_Player_Items_List_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature");

	Params::UI_Tavern_Mercenaries_C_BndEvt__UI_Tavern_Inventory_Player_Items_List_K2Node_ComponentBoundEvent_1_OnListEntryInitializedDynamic__DelegateSignature Parms{};

	Parms.Item_0 = Item_0;
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_0_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_0_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_0_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_0_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_0_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_0_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_1_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_1_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_1_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_1_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_1_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_1_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_2_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_2_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_2_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_2_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_2_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_2_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_3_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_3_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_3_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_3_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_3_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_3_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_4_K2Node_ComponentBoundEvent_10_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_4_K2Node_ComponentBoundEvent_10_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_4_K2Node_ComponentBoundEvent_10_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Button_4_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Button_4_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Button_4_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_CheckBox_K2Node_ComponentBoundEvent_12_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_CheckBox_K2Node_ComponentBoundEvent_12_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_CheckBox_K2Node_ComponentBoundEvent_12_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::UI_Tavern_Mercenaries_C_BndEvt__UI_Tavern_Mercenaries_CheckBox_K2Node_ComponentBoundEvent_12_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.BndEvt__UI_Tavern_Mercenaries_Player_Items_List_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::BndEvt__UI_Tavern_Mercenaries_Player_Items_List_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature(class UObject* Item_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "BndEvt__UI_Tavern_Mercenaries_Player_Items_List_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature");

	Params::UI_Tavern_Mercenaries_C_BndEvt__UI_Tavern_Mercenaries_Player_Items_List_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature Parms{};

	Parms.Item_0 = Item_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Tavern_Mercenaries_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.ED Check Arming Points_Event
// (BlueprintCallable, BlueprintEvent)

void UUI_Tavern_Mercenaries_C::ED_Check_Arming_Points_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "ED Check Arming Points_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Event Setup DressUp Darling
// (BlueprintCallable, BlueprintEvent)

void UUI_Tavern_Mercenaries_C::Event_Setup_DressUp_Darling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Event Setup DressUp Darling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.ExecuteUbergraph_UI_Tavern_Mercenaries
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::ExecuteUbergraph_UI_Tavern_Mercenaries(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "ExecuteUbergraph_UI_Tavern_Mercenaries");

	Params::UI_Tavern_Mercenaries_C_ExecuteUbergraph_UI_Tavern_Mercenaries Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get Player Character
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FStr_Passport_Character1         ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash)

struct FStr_Passport_Character1 UUI_Tavern_Mercenaries_C::Get_Player_Character()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get Player Character");

	Params::UI_Tavern_Mercenaries_C_Get_Player_Character Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get Player Inventory
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FStr_Inventory             ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, HasGetValueTypeHash)

const struct FStr_Inventory UUI_Tavern_Mercenaries_C::Get_Player_Inventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get Player Inventory");

	Params::UI_Tavern_Mercenaries_C_Get_Player_Inventory Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Bevor_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Bevor_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Bevor_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Bevor_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Coif_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Coif_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Coif_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Coif_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Cuirass_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Cuirass_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Cuirass_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Cuirass_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Cuisse_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Cuisse_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Cuisse_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Cuisse_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Doublet_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Doublet_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Doublet_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Doublet_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Fould_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Fould_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Fould_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Fould_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Gauntlet_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Gauntlet_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Gauntlet_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Gauntlet_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Greave_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Greave_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Greave_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Greave_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Hauberk_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Hauberk_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Hauberk_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Hauberk_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Helmet_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Helmet_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Helmet_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Helmet_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Hood_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Hood_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Hood_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Hood_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Hosen_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Hosen_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Hosen_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Hosen_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Overcoat_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Overcoat_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Overcoat_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Overcoat_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Shoe_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Shoe_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Shoe_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Shoe_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Spaulder_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Spaulder_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Spaulder_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Spaulder_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Standart_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Standart_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Standart_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Standart_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_Vambrace_Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_Vambrace_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_Vambrace_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_Vambrace_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_WeaponL_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_WeaponL_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_WeaponL_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_WeaponL_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_WeaponR_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_WeaponR_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_WeaponR_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_WeaponR_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_WeaponSheathedL2_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_WeaponSheathedL2_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_WeaponSheathedL2_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_WeaponSheathedL2_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_WeaponSheathedR1_1_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_WeaponSheathedR1_1_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_WeaponSheathedR1_1_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_WeaponSheathedR1_1_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Get_Button_WeaponSheathedR1_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::Get_Button_WeaponSheathedR1_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Get_Button_WeaponSheathedR1_Visibility");

	Params::UI_Tavern_Mercenaries_C_Get_Button_WeaponSheathedR1_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush");

	Params::UI_Tavern_Mercenaries_C_GetBrush Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_0");

	Params::UI_Tavern_Mercenaries_C_GetBrush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_1
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_1");

	Params::UI_Tavern_Mercenaries_C_GetBrush_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_2
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_2");

	Params::UI_Tavern_Mercenaries_C_GetBrush_2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_3
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_3");

	Params::UI_Tavern_Mercenaries_C_GetBrush_3 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_4
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_4");

	Params::UI_Tavern_Mercenaries_C_GetBrush_4 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_5
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_5");

	Params::UI_Tavern_Mercenaries_C_GetBrush_5 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_6
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_6");

	Params::UI_Tavern_Mercenaries_C_GetBrush_6 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetBrush_7
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUI_Tavern_Mercenaries_C::GetBrush_7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetBrush_7");

	Params::UI_Tavern_Mercenaries_C_GetBrush_7 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetCheckedState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ECheckBoxState                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ECheckBoxState UUI_Tavern_Mercenaries_C::GetCheckedState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetCheckedState");

	Params::UI_Tavern_Mercenaries_C_GetCheckedState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Tavern_Mercenaries_C::GetText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetText");

	Params::UI_Tavern_Mercenaries_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Tavern_Mercenaries_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetText_0");

	Params::UI_Tavern_Mercenaries_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetText_1
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUI_Tavern_Mercenaries_C::GetText_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetText_1");

	Params::UI_Tavern_Mercenaries_C_GetText_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_Tavern_Mercenaries_C::GetValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetValue");

	Params::UI_Tavern_Mercenaries_C_GetValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetValue_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UUI_Tavern_Mercenaries_C::GetValue_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetValue_0");

	Params::UI_Tavern_Mercenaries_C_GetValue_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_0");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_1");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_2");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_3
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_3");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_3 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_4
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_4");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_4 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_5
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_5");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_5 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_6
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_6");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_6 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_7
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_7");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_7 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.GetVisibility_8
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Tavern_Mercenaries_C::GetVisibility_8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "GetVisibility_8");

	Params::UI_Tavern_Mercenaries_C_GetVisibility_8 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "PreConstruct");

	Params::UI_Tavern_Mercenaries_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Remove Armor From Slot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const EArmorSlots_Enum                  Slot_0                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::Remove_Armor_From_Slot(const EArmorSlots_Enum Slot_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Remove Armor From Slot");

	Params::UI_Tavern_Mercenaries_C_Remove_Armor_From_Slot Parms{};

	Parms.Slot_0 = Slot_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Reset Character to 0
// (BlueprintCallable, BlueprintEvent)

void UUI_Tavern_Mercenaries_C::Reset_Character_to_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Reset Character to 0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Tavern_Mercenaries.UI_Tavern_Mercenaries_C.Set Up Trader Item
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Tavern_Mercenaries_C::Set_Up_Trader_Item(class UObject* Item_0, class UObject* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tavern_Mercenaries_C", "Set Up Trader Item");

	Params::UI_Tavern_Mercenaries_C_Set_Up_Trader_Item Parms{};

	Parms.Item_0 = Item_0;
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}

}

