#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Sword_Guard_BA

#include "Basic.hpp"

#include "Modular_Sword_Guard_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Sword_Guard_BA.Weapon_Sword_Guard_BA_C
// 0x0000 (0x0448 - 0x0448)
class AWeapon_Sword_Guard_BA_C final : public AModular_Sword_Guard_Master_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Sword_Guard_BA_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Sword_Guard_BA_C")
	}
	static class AWeapon_Sword_Guard_BA_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Sword_Guard_BA_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Sword_Guard_BA_C;

}

