#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Part_Mace_Strap_I

#include "Basic.hpp"

#include "Modular_Weapon_Module_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Part_Mace_Strap_I.Weapon_Part_Mace_Strap_I_C
// 0x0000 (0x0420 - 0x0420)
class AWeapon_Part_Mace_Strap_I_C final : public AModular_Weapon_Module_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Part_Mace_Strap_I_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Part_Mace_Strap_I_C")
	}
	static class AWeapon_Part_Mace_Strap_I_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Part_Mace_Strap_I_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Part_Mace_Strap_I_C;

}

