#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Part_Mace_Grip_C_M

#include "Basic.hpp"

#include "Weapon_Part_Mace_Grip_A_M_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Part_Mace_Grip_C_M.Weapon_Part_Mace_Grip_C_M_C
// 0x0000 (0x05F8 - 0x05F8)
class AWeapon_Part_Mace_Grip_C_M_C final : public AWeapon_Part_Mace_Grip_A_M_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Part_Mace_Grip_C_M_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Part_Mace_Grip_C_M_C")
	}
	static class AWeapon_Part_Mace_Grip_C_M_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Part_Mace_Grip_C_M_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Part_Mace_Grip_C_M_C;

}

