#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Module_Casted_Grip_DC

#include "Basic.hpp"

#include "Weapon_Module_Casted_Grip_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Module_Casted_Grip_DC.Weapon_Module_Casted_Grip_DC_C
// 0x0000 (0x05F8 - 0x05F8)
class AWeapon_Module_Casted_Grip_DC_C final : public AWeapon_Module_Casted_Grip_Master_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Module_Casted_Grip_DC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Module_Casted_Grip_DC_C")
	}
	static class AWeapon_Module_Casted_Grip_DC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Module_Casted_Grip_DC_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Module_Casted_Grip_DC_C;

}

