#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Sword_Pommel_U

#include "Basic.hpp"

#include "Modular_Sword_Pommel_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Sword_Pommel_U.Weapon_Sword_Pommel_U_C
// 0x0000 (0x0450 - 0x0450)
class AWeapon_Sword_Pommel_U_C final : public AModular_Sword_Pommel_Master_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Sword_Pommel_U_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Sword_Pommel_U_C")
	}
	static class AWeapon_Sword_Pommel_U_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Sword_Pommel_U_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Sword_Pommel_U_C;

}

